version: '3.3'

services:
  monitor-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here